# Generated by Django 5.2.4 on 2025-07-07 09:27

import produk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to=produk.models.upload_to_uuid),
        ),
    ]
