# Generated by Django 5.2.4 on 2025-07-07 12:52

import uuid
from django.db import migrations, models



def generate_uuids(apps, schema_editor):
    Kategori = apps.get_model('produk', 'Kategori')
    for kategori in Kategori.objects.all():
        kategori.uuid = uuid.uuid4()
        kategori.save()

def generate_produk_uuids(apps, schema_editor):
    Produk = apps.get_model('produk', 'Produk')
    for produk in Produk.objects.all():
        produk.uuid = uuid.uuid4()
        produk.save()

class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_alter_produk_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(generate_uuids),
        migrations.AddField(
            model_name='produk',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(generate_produk_uuids),
    ]
