# Generated by Django 5.2.4 on 2025-07-07 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_kategori_uuid_produk_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaketSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paket_soal', to='produk.produk')),
            ],
        ),
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.TextField()),
                ('opsi_a', models.CharField(max_length=500)),
                ('opsi_b', models.CharField(max_length=500)),
                ('opsi_c', models.CharField(max_length=500)),
                ('opsi_d', models.CharField(max_length=500)),
                ('jawaban_benar', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('pembahasan', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='produk.paketsoal')),
            ],
        ),
    ]
