# Generated by Django 5.2.4 on 2025-07-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_paketsoal_soal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paketsoal',
            name='produk',
        ),
        migrations.AddField(
            model_name='produk',
            name='paket_soal',
            field=models.ManyToManyField(blank=True, related_name='produks', to='produk.paketsoal'),
        ),
        migrations.AddField(
            model_name='produk',
            name='tanggal_diperbarui',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
