# Generated by Django 5.2.4 on 2025-11-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0006_kategori_level_kategori_lft_kategori_rght_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
