# Generated by Django 5.2.4 on 2025-11-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0007_produk_is_active'),
    ]

    def deactivate_products_without_paket(apps, schema_editor):
        Produk = apps.get_model('produk', 'Produk')
        # Nonaktifkan produk yang belum punya paket soal
        Produk.objects.filter(paket_soal__isnull=True).update(is_active=False)

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(deactivate_products_without_paket, migrations.RunPython.noop),
    ]
