# Generated by Django 5.2.4 on 2025-11-26 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0008_alter_produk_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paketsoal',
            name='penjual',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='paket_soalnya', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paketsoal',
            name='tanggal_dibuat',
            field=models.DateTimeField(auto_now_add=True, default="2025-11-26 14:22:00"),
            preserve_default=False,
        ),
    ]
