# Generated by Django 5.2.4 on 2025-07-10 02:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produk', '0005_remove_paketsoal_produk_produk_paket_soal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('waktu_selesai', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.paketsoal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JawabanUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_dipilih', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('benar', models.BooleanField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hasil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to='cbt.hasilujian')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.soal')),
            ],
        ),
    ]
